### PR TITLE
fix typo in README.md

### PR DESCRIPTION
**Pull request by ComputerDruid**
This change is [Reviewable](https://reviewable.io/reviews/panicbit/custom_debug/14)

### CODE REVIEW

**Comment by panicbit** [comment]
Thanks! :)

**Comment by fasterthanlime** [comment]
Note that the mistake is still visible on lib.rs / crates.io: 

  * https://lib.rs/crates/custom_debug
  * https://crates.io/crates/custom_debug

Maybe doing a patch release (the `z` in `x.y.z`) would be a good idea.

**Comment by panicbit** [comment]
Oh hi Amos ❤️. Will get my butt moving for a patch release ASAP.

**Comment by panicbit** [comment]
Released as [0.5.1 to crates.io](https://crates.io/crates/custom_debug/0.5.1)

**Comment by fasterthanlime** [comment]
> Released as [0.5.1 to crates.io](https://crates.io/crates/custom_debug/0.5.1)

Looks great, thanks so much! 💜

(I noticed this as I was updating "Reading files the hard way", which uses this crate!)

**Pull request merged**
